config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  mount LibraryDesign::Engine => "/library_design"

  # Defines the root path route ("/")

  get '' => 'home#index', as: :root
  get 'uk-general-elections' => 'home#index', as: :home
  
  get 'uk-general-elections/years' => 'year#index', as: :year_list
  get 'uk-general-elections/years/:year' => 'year#show', as: :year_show
  
  get 'uk-general-elections/general-elections' => 'general_election#index', as: :general_election_list
  get 'uk-general-elections/general-elections/:general_election' => 'general_election#show', as: :general_election_show
  
  get 'uk-general-elections/general-elections/:general_election/elections' => 'general_election_election#index', as: :general_election_election_list
  
  get 'uk-general-elections/general-elections/:general_election/parties' => 'general_election_party#index', as: :general_election_party_list
  get 'uk-general-elections/general-elections/:general_election/parties/:party' => 'general_election_party#show', as: :general_election_party_show
  
  get 'uk-general-elections/elections' => 'election#index', as: :election_list
  get 'uk-general-elections/elections/:election' => 'election#show', as: :election_show
  
  get 'uk-general-elections/constituencies' => 'constituency#index', as: :constituency_list
  get 'uk-general-elections/constituencies/:constituency' => 'constituency#show', as: :constituency_show
  
  get 'uk-general-elections/parties' => 'party#index', as: :party_list
  get 'uk-general-elections/parties/:party' => 'party#show', as: :party_show
  
  get 'uk-general-elections/letters' => 'letter#index', as: :letter_list
  get 'uk-general-elections/letters/:letter' => 'letter#show', as: :letter_show
  
  get 'uk-general-elections/surnames' => 'surname#index', as: :surname_list
  get 'uk-general-elections/surnames/:surname' => 'surname#show', as: :surname_show
  
  get 'uk-general-elections/candidate-names' => 'candidate_name#index', as: :candidate_name_list
  get 'uk-general-elections/candidate-names/:candidate_name' => 'candidate_name#show', as: :candidate_name_show
  
  get 'uk-general-elections/meta' => 'meta#index', as: :meta_list
  get 'uk-general-elections/meta/schema' => 'meta#schema', as: :meta_schema
  get 'uk-general-elections/meta/cookies' => 'meta#cookies', as: :meta_cookies
end

app/models/election.rb
# == Schema Information
#
# Table name: elections
#
#  id                  :integer          not null, primary key
#  is_uncontested      :boolean          default(FALSE)
#  turnout             :float(24)
#  constituency_id     :integer          not null
#  general_election_id :integer          not null
#
# Foreign Keys
#
#  fk_constituency      (constituency_id => constituencies.id)
#  fk_general_election  (general_election_id => general_elections.id)
#
class Election < ApplicationRecord
  
  belongs_to :general_election
  belongs_to :constituency
  
  def candidacies
    Candidacy.find_by_sql(
    "
      SELECT c.*, p.name as party_name, cn.name as candidate_name_display
      FROM candidacies c, parties p, candidate_names as cn
      WHERE c.election_id = #{self.id}
      AND c.party_id = p.id
      AND c.candidate_name_id = cn.id
      ORDER BY c.votes DESC;
    "
    )
  end
  
  def name_with_general_election
    general_election_name
  end
  
  def full_name
    full_name = general_election_name
    full_name += ' - '
    full_name += constituency_name
  end
end

app/controllers/election_controller.rb
class ElectionController < ApplicationController
  
  def index
    @elections = Election.find_by_sql(
      "
        SELECT e.*, y.year AS year, ge.name AS general_election_name, c.name AS constituency_name
        FROM elections e, constituencies c, general_elections ge, years y
        WHERE e.constituency_id = c.id
        AND e.general_election_id = ge.id
        AND ge.year_id = y.id
        ORDER BY y.year, ge.name, c.name;
      "
    )
    @page_title = 'Elections'
    @description = 'Elections.'
    @crumb << {label: @page_title, url: nil}
  end
  
  def show
    election_id = params[:election]
    @election = Election.find_by_sql([
      "
        SELECT e.*, y.year AS year, y.id AS year_id, ge.name AS general_election_name, c.name AS constituency_name
        FROM elections e, constituencies c, general_elections ge, years y
        WHERE e.id = ?
        AND e.constituency_id = c.id
        AND e.general_election_id = ge.id
        AND ge.year_id = y.id
        ORDER BY y.year, ge.name, c.name;
      ", election_id
    ]).first

    @page_title = "#{@election.general_election_name} - #{@election.constituency_name}"
    @description = "Election in #{@election.constituency_name} held as part of the #{@election.general_election_name}."
    @section = 'general-elections'
    @crumb << {label: 'General elections', url: general_election_list_url}
    @crumb << {label: @election.general_election_name, url: general_election_show_url( :general_election => @election.general_election )}
    @crumb << {label: @election.constituency_name, url: nil}
    
  end
end

app/views/election/_election.html.erb
<%= content_tag( 'li', link_to( election.constituency_name, election_show_url( :election => election ) ) ) %>

app/views/election/_election_with_general_election.html.erb
<%= content_tag( 'li', link_to( election_with_general_election.name_with_general_election, election_show_url( :election => election_with_general_election ) ) ) %>

app/views/election/_election_with_general_election_and_constituency.html.erb
<%= content_tag( 'li', link_to( election_with_general_election_and_constituency.full_name, election_show_url( :election => election_with_general_election_and_constituency ) ) ) %>

app/views/election/index.html.erb
<%= content_tag( 'p', list_item_count_sentence( 'election', @elections.size ) ) %>

<ol class="unnumbered link-list">
	<%= render :partial => 'election_with_general_election_and_constituency', :collection => @elections %>
</ol>

app/views/election/show.html.erb
<div class="overflow-auto">
	<table class="table key-value">
		<tbody>
			<tr>
				<%= content_tag( 'td', 'Year' ) %>
				<%= content_tag( 'td', link_to( @election.year, year_show_url( :year => @election.year_id ) ) ) %>
			</tr>
			<tr>
				<%= content_tag( 'td', 'General election' ) %>
				<%= content_tag( 'td', link_to( @election.general_election_name, general_election_show_url( :general_election => @election.general_election_id ) ) ) %>
			</tr>
			<tr>
				<%= content_tag( 'td', 'Constituency' ) %>
				<%= content_tag( 'td', link_to( @election.constituency_name, constituency_show_url( :constituency => @election.constituency_id ) ) ) %>
			</tr>
			<tr>
				<%= content_tag( 'td', 'Turnout' ) %>
				<td>
					<% if @election.is_uncontested -%>
						Election uncontested
					<% else -%>
						<%= @election.turnout %>%
					<% end -%>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<%= content_tag( 'h2', 'Results' ) %>
<div class="overflow-auto">
	<table class="table">
		<thead>
			<tr>
				<%= content_tag( 'td', 'Candidate' ) %>
				<%= content_tag( 'td', 'Party' ) %>
				<%= content_tag( 'td', 'Votes', :class => 'number' ) unless @election.is_uncontested %>
			</tr>
		</thead>
		<tbody>
			<%= render :partial => 'candidacy/candidacy', :collection => @election.candidacies %>
		</tbody>
	</table>
</div>